version: '3.4'


services:
  nginx:
    image: nginx:stable
    container_name: academy-nginx
    volumes:
      - ./.deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.deploy/nginx/conf.d/nginx_rules.conf:/etc/nginx/conf.d/nginx_rules.conf
    ports:
      - "80:80"
  mysql:
    image: mysql:8.3
    container_name: academy-mysql
    environment:
      MYSQL_USER: academy
      MYSQL_DATABASE: academy
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"


volumes:
  mysql:
    name: academy-mysql
