version: '3.4'


services:
  nginx:
    image: nginx:stable
    container_name: academy-nginx
    volumes:
      - ./.deploy/nginx/:/etc/nginx/conf.d/
    ports:
      - "80:80"
#  postgres:
#    image: postgres
#    container_name: academy-postgres
#    environment:
#      POSTGRES_USER: academy
#      POSTGRES_PASSWORD: academy
#      PGDATA: /var/lib/postgresql/data/pgdata
#    volumes:
#      - postgres:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"


#volumes:
#  postgres:
#    name: academy-postgresql
