# Generated by Django 5.0.2 on 2024-03-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_public_remove_task_autocheck_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tutor',
            new_name='author',
        ),
    ]
