# Generated by Django 5.0.3 on 2024-03-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_description_task_format_in_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Закрыт'), (1, 'Опубликован')], default=0, verbose_name='Опубликован'),
        ),
    ]
