# Generated by Django 5.0.3 on 2024-03-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_task_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='ram_limit',
        ),
    ]
