# Generated by Django 5.0.3 on 2024-03-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_testcase_ram_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='output',
            field=models.TextField(blank=True, verbose_name='Результат решения'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Успешно'), (1, 'Неверный ответ'), (2, 'Не валидный код'), (3, 'Превышен лимит по времени')], verbose_name='Статус попытки'),
        ),
    ]
