# Generated by Django 5.0.3 on 2024-03-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_attempt_test_case'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupCourseTopic',
        ),
    ]
