# Generated by Django 5.0.3 on 2024-03-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_delete_groupcoursetopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='autocheck',
            field=models.BooleanField(default=False, verbose_name='Авто-проверка'),
        ),
    ]
