# Generated by Django 5.0.3 on 2024-03-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_task_autocheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='autocheck',
        ),
        migrations.AddField(
            model_name='task',
            name='autoreview',
            field=models.PositiveSmallIntegerField(choices=[(0, 'нет'), (1, 'да')], default=0, verbose_name='Авто-проверка'),
        ),
    ]
