# Generated by Django 5.0.3 on 2024-03-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_task_autocheck_task_autoreview'),
        ('users', '0006_alter_student_is_active_alter_teacher_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Успешно'), (1, 'Неверный ответ'), (2, 'Не валидный код'), (3, 'Превышен лимит по времени'), (4, 'На проверке'), (5, 'Отменено')], verbose_name='Статус попытки'),
        ),
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together={('student', 'task')},
        ),
    ]
