# Generated by Django 5.0.3 on 2024-03-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_attempt_status_alter_attempt_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
