# Generated by Django 5.0.3 on 2024-03-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_attempt_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Успешно'), (1, 'Неверный ответ'), (2, 'Не валидный код'), (3, 'Превышен лимит по времени'), (4, 'На проверке')], verbose_name='Статус попытки'),
        ),
    ]
