# Generated by Django 5.0.3 on 2024-03-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_attempt_created_at_alter_attempt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Классная'), (1, 'Домашняя'), (2, 'Дополнительная')], default=0, verbose_name='Тип'),
        ),
    ]
