# Generated by Django 5.0.3 on 2024-03-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (мин.)'),
        ),
    ]
