# Generated by Django 5.0.3 on 2024-03-23 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_topic_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('name', models.CharField(max_length=128, verbose_name='Название файла')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.topic')),
            ],
        ),
    ]
