# Generated by Django 5.0.3 on 2024-03-23 11:37

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_topicattachment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicattachment',
            name='file',
            field=models.FileField(upload_to=courses.models.topic_attachment_path, verbose_name='Файл'),
        ),
    ]
