# Generated by Django 5.0.2 on 2024-03-03 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('courses', '0002_remove_course_public_remove_task_autocheck_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='teacher_name',
        ),
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.IntegerField(blank=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='class',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='class',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
