# Generated by Django 5.0.2 on 2024-03-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_class_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.IntegerField(unique=True, verbose_name='Код'),
        ),
    ]
