# Generated by Django 5.0.2 on 2024-03-04 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_alter_class_code'),
        ('courses', '0003_rename_tutor_course_author'),
        ('users', '0004_student_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('code', models.IntegerField(unique=True, verbose_name='Код')),
                ('teacher_name', models.CharField(blank=True, max_length=150, verbose_name='ФИО Учителя')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.teacher')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='GroupCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.group')),
            ],
            options={
                'verbose_name': 'Курс класса',
                'verbose_name_plural': 'Курсы классов',
                'unique_together': {('group', 'course')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='courses',
            field=models.ManyToManyField(related_name='course_groups', through='classes.GroupCourses', to='courses.course'),
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
            options={
                'verbose_name': 'Ученик класса',
                'verbose_name_plural': 'Ученики классов',
                'unique_together': {('group', 'student')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(related_name='student_groups', through='classes.GroupStudent', to='users.student'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
