# Generated by Django 5.0.2 on 2024-03-07 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_group_groupcourses_group_courses_groupstudent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='course',
        ),
    ]
