# Generated by Django 5.0.3 on 2024-03-15 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_remove_group_course'),
        ('courses', '0005_topic_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.group', unique=True)),
            ],
            options={
                'verbose_name': 'Курс класса',
                'verbose_name_plural': 'Курсы классов',
            },
        ),
        migrations.AlterField(
            model_name='group',
            name='courses',
            field=models.ManyToManyField(related_name='course_groups', through='classes.GroupCourse', to='courses.course'),
        ),
        migrations.DeleteModel(
            name='GroupCourses',
        ),
    ]
