# Generated by Django 5.0.3 on 2024-03-15 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_groupcourse_alter_group_courses_delete_groupcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcourse',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classes.group'),
        ),
    ]
