# Generated by Django 5.0.3 on 2024-03-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0009_alter_groupcourse_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupstudent",
            name="main",
            field=models.BooleanField(default=True, verbose_name="Основной"),
        ),
    ]
