# Generated by Django 5.0.3 on 2024-03-16 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0010_groupstudent_main"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupstudent",
            name="main",
            field=models.BooleanField(default=False, verbose_name="Основной"),
        ),
    ]
