# Generated by Django 5.0.3 on 2024-03-17 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_groupcourse_active_alter_groupcourse_group'),
        ('courses', '0008_remove_testcase_ram_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_courses', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='groupcourse',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_courses', to='classes.group'),
        ),
    ]
