# Generated by Django 5.0.3 on 2024-03-17 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_alter_groupcourse_course_alter_groupcourse_group'),
        ('courses', '0011_delete_groupcoursetopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='courses',
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='courses.course'),
        ),
    ]
