name: CI
on:
    push:
      branches:
      - dev

jobs:
    deploy_prod:
      name: deploy to prod
      runs-on: ubuntu-18.04

      steps:
      - name: Run deploy.sh
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.HOST}}
          port: ${{secrets.PORT}}
          user: ${{secrets.USER}}
          private_key: ${{secrets.PRIVATE_KEY}}
          command: cd /opt/academy/ && bash deploy.sh
 
