name: CI
on:
   # События, которые запускают jobs
    push:
      branches:
      - master

jobs:
    # Название job вы можете назвать как угодно
    my_deploy_job:
      name: deploy to staging
      runs-on: ubuntu-18.04

      steps:
      - name: SSH Command
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.HOST}}
          port: ${{secrets.PORT}}
          user: ${{secrets.USER}}
          private_key: ${{secrets.PRIVATE_KEY}}
          command: cd /opt/academy/ && bash deploy.sh

            
